### ISSUE TITLE
Pharmaverse Inclusion Criteria Checklist

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#445]
### Hosting & Licensing

- [x]  Acceptable open source license: [MIT](https://github.com/pharmaR/riskassessment/blob/master/LICENSE.md)
- [x]  Hosted publicly: Codebase available on [GitHub](https://github.com/pharmaR/riskassessment) since 2020

### Documentation

- [x] Exported [functions must have docs](https://pharmar.github.io/riskassessment/reference/index.html) that [pass R CMD Check](https://github.com/pharmaR/riskassessment/actions/)
- [x] Package [website](https://rinpharma.shinyapps.io/riskassessment/), with [vignettes](https://pharmar.github.io/riskassessment/articles/index.html)

### Version Compatibility and Dependencies

- [x] Continuous Integration (CI) action to test [R CMD Check](https://github.com/pharmaR/riskassessment/actions/) with extra workflows
- [x] Incremental, semantic [versioning used](https://github.com/pharmaR/riskassessment/blob/8563df1717e94676db59313b3b93b67809ac5c74/dev/02_dev.R#L193), following strategies from r-pkgs.org
- [x] Dependencies [clearly documented](https://github.com/pharmaR/riskassessment/blob/master/DESCRIPTION#L38-L63), and [intentionally limited](https://github.com/pharmaR/riskassessment/pull/323/files#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c) to the most necessary.

### Support and Maintenance

- [x] The R Validation Hub ensures the package is maintained. Current dev team consists of about 7 people with representation from Pharma companies around the globe. The code base actively developed with a roadmap and bi-weekly meeting, with established slack channel (happy to invite collaborators via slack). 

- [x] `master` and [`dev`](https://github.com/pharmaR/riskassessment/tree/dev) are both protected, restricted to a set of maintainers able to admit changes to `master`.

![image](https://user-images.githubusercontent.com/17878953/221685644-11ef547d-251e-4574-97fa-b25435246119.png)

- [x] The `master` and `dev` branches have a [slurry of automated CI](https://github.com/pharmaR/riskassessment/tree/master/.github/workflows), including `R-CMD-CHECK` on Windows, Linux, and MacOS.

### CRAN Acceptability

- [] [On CRAN](https://cran.r-project.org/web/packages/available_packages_by_name.html). Is this a requirement? There seems to be a number of packages included in the pharmaverse that are not on CRAN such as {teal} and {tidytlg}.

## Recommended development practices

- [ ] Lintr / styling implemented. Common vocabulary across modules was loosely achieved.
- [x] synthetic CDISC. Not needed since the app doesn't handle clinical data
- [x] [renv](https://github.com/pharmaR/riskassessment/blob/master/renv.lock) used to ensure consistent development environment
- [x] All methods / processes / environments are NOT specific to any one company

**Comment by rossfarrugia** [comment]
@AARON-CLARK thanks for taking the time to compile this list! on the CRAN topic, is it that your team is not planning to submit {riskassessment} and {riskmetric} to CRAN at all, or that you just haven't got to that stage yet?

It is a debatable topic for pharmaverse inclusion criteria, so happy to take this back to the council to see if we should update this. For the pharmaverse packages you mentioned I understand all are planned to submit to CRAN, but again could debate that it's not really needed anyway.

**Comment by AARON-CLARK** [comment]
>thanks for taking the time to compile this list!

@rossfarrugia No problem. Our pleasure. 

Yes, so `riskmetric` is already on CRAN, and submitting `{riskassessment}` to CRAN isn't on our current roadmap, though it is possible. We just made intentional decisions for this package to be maintained (right now) using dependencies defined via `{renv}` and the `renv.lock` instead of the latest version of each dependency on CRAN. The goal was to provide consistency to our developers and any users who hoped to deploy this app internally for their org. Our installation instructions [discusses this briefly](https://pharmar.github.io/riskassessment/#installation) and is well supported with a vignette on [how to use renv](https://pharmar.github.io/riskassessment/articles/dev_renv.html) with the project.

Like you said, I think the topic has pros and cons and would make for a lively debate amongst wg members. Perhaps the decision should be made within each working group? Do the rest of the validation pkgs (like `covtracer`, `thevalidatoR`, and `valtools`) also hope to release on CRAN? It seems like `riskmetric` would be the only validation pkg on CRAN out of the bunch. 

OR perhaps the wg members should determine what outcomes are attractive about submitting to CRAN and see if they are achievable without actually submitting to CRAN? lol for example, maybe pkgs just need to pass an extra set of tests/checks like these [CRAN submission prep checks](https://github.com/ThinkR-open/prepare-for-cran#tldr) documented by Colin Fay @ ThinkR.

**Comment by rossfarrugia** [comment]
All fair points! I'm not actually sure about those validation packages, we're in process of re-reviewing all of our current packages since we only recently released the inclusion criteria. Will raise this topic to see if we really need this criteria.

**Comment by AARON-CLARK** [comment]
Closing because the pkg in on Pharmaverse 🎉
